### PR TITLE
Improve some features and fix some issues.

### PR DESCRIPTION
**Pull request by boyw165**
Hi @d11wtq 

I like your work which is very lightweight so I made some changes:

* Add grizzl group.
* Add grizzl-imenu for imenu.
* Support face customization and fix deprecated faces.
   <https://github.com/d11wtq/grizzl/issues/18>
* Support scrollable result display in minibuffer and truncate display.
   <https://github.com/d11wtq/grizzl/issues/10>
   <https://github.com/d11wtq/grizzl/issues/13>
   <https://github.com/d11wtq/grizzl/issues/14>
   <https://github.com/d11wtq/grizzl/issues/15>
* Support `grizzl-completion-read-gui` as a GUI provider (delegate searching job to other backend).
* Support `grizzl-read-update-hook' to info hooks the current result.
* Slightly improve performance by using idle timer to do searching job instead
  of do it in post-command.

TODO:
-----
* Highlight matched characters.
  <https://github.com/d11wtq/grizzl/issues/5>

### CODE REVIEW

**Comment by bbatsov** [comment]
Grizzl is pretty much dead lately. I've been thinking about forking it for a while, but I'm already super busy. I do think, however, think that someone should fork it and take it over if this project is to have any chance.

**Comment by d11wtq** [comment]
Yeah, unfortunately that's true. I'm not actively using Emacs at the moment and so don't have the motivation to work on Grizzl in what small amount of free time I have. I would like to see the project continue under a different maintainer, however.

**Comment by boyw165** [comment]
Hmm @@;

**Comment by d11wtq** [comment]
@boyw165 I don't. Perhaps I could add you and @bbatsov as collaborators, or transfer the project to one of you? I think the best way for open source projects to survive is to make sure multiple people are involved.

**Comment by bbatsov** [comment]
I'm fine with adding us as maintainers and keeping the project here for the time being. Please, grant us the rights to add more maintainers if needed.

**Comment by boyw165** [comment]
I'm cool too.

**Comment by d11wtq** [comment]
I've added you as collaborators. If that doesn't give you rights to add other collaborators, I'll move the projects to an organization under 'grizzl/grizzl' and 'grizzl/fiplr'.

**Comment by boyw165** [comment]
Thank you. So what do you guys thank about this pull request?

**Comment by bbatsov** [comment]
@boyw165 The scope of the PR is too big. I'd suggest breaking it into smaller PRs - one for every feature. I'll also suggest squashing related commits together.

@d11wtq I can't add collaborators, so it seems a grizzl org will be a better idea. I can imagine that over time we might end up with other grizzl related projects as well.

**Comment by bbatsov** [comment]
@boyw165 I'll close this PR. Submit the related changes as separate PRs.

**Comment by boyw165** [comment]
@bbatsov Ok, I'll submit later since too busy recently. :beers:

**Pull request closed without merging**
